name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_SERVICE_ACCOUNT_WOHNUNGSPROTOKOLL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WOHNUNGSPROTOKOLL }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT_WOHNUNGSPROTOKOLL}" > ${HOME}/firebase-key.json
          firebase deploy --only hosting --project wohnungsprotokoll-8eefd --token "$(firebase login:ci || true)"
